// Async Api Call Constatnt.
export const FETCH_REQUEST='FETCH_REQUEST';
export const FETCH_SUCCESS='FETCH_SUCCESS';
export const FETCH_FAILED='FETCH_FAILED';

export const FETCH_REQUEST_CATEGORY='FETCH_REQUEST_CATEGORY';
export const FETCH_SUCCESS_CATEGORY='FETCH_SUCCESS_CATEGORY';
export const FETCH_FAILED_CATEGORY='FETCH_FAILED_CATEGORY';

// Cart Related Constant
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const INCREASE_QUANTITY_IN_CART='INCREASE_QUANTITY_IN_CART';
export const DECREASE_QUANTITY_FROM_CART='DECREASE_QUANTITY_FROM_CART';

// Load Products.
export const LOAD_FEATURED_PRODUCT='LOAD_FEATURED_PRODUCT';
export const SELECT_PRICE='SELECT_PRICE';
export const SELECT_CATEGORY='SELECT_CATEGORY';
export const FILTER_CATEGORY_PRICE_PRODUCT='FILTER_CATEGORY_PRICE_PRODUCT';